### ISSUE TITLE
请求一个问题 如果是 开启了缓存在取到数据后加到了 数据源了 然后又开始请求了新数据又加到了数据源了 那么缓存的数据不是应该删掉吗 这时候怎么处理合适呢  ，希望再完善下 就是没网取缓存 有网请求  请求失败取缓存 

### ISSUE THREAD

**Issue by ws1227** [ClaudeLi/TTNetworking#1]
说的对啊如果是加载数据 就需要加个全局bool在返回数据的block里 加上判断就ok了  刷新就清空 加载就不清空 另外 我觉得在请求前加上 判断网络状态会更好

**Comment by ClaudeLi** [comment]
我在方法的注释上写了 <若开启缓存，先读取本地缓存数据，再进行网络请求> 不管请求成功还是失败，在请求前都已经返回了上次请求的缓存数据， 这么做是考虑在页面还在网络请求的时候就有数据显示 不想让出现空白页， 在请求成功的Block回调里 会收到两次数据，在接收数据的时候 先清空接收数据的容器<字典/数组..>  再接收数据 刷新页面。
